### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by btrose98** [btrose98/Family-Wheels-Planner---Android#1]
- [x] Add Unit tests
- [x] fix network exception unit test
- [x] Add instrumented tests
- [ ] Fix secrets.properties file missing build error in actions
- [ ] Setup jacoco test coverage report
- [ ] setup emulator in CI for instrumented tests
